### PR TITLE
fix: handle txt values properly

### LINKED ISSUE #169: TXT entry with an empty value is shown as a valueless entry
Steps to reproduce:
run this example:
https://gitlab.com/hrzlgnm/m/-/blob/8b775f77a381fd5f9e84e8666fa05e7a6d97a704/avahidings/client-publish-service.c

### PR DESCRIPTION
**Pull request by hrzlgnm**
- show only valueless txt properties withthout a value
- escape binary values as far as possible

Closes #169

### CODE REVIEW

File: src-tauri/src/main.rs [hunk 1]
```diff
@@ -58,16 +58,52 @@ fn timestamp_millis() -> u64 {
...
+            }
+        })
+        .collect()
+}
+
+fn bytes_option_to_string_option_with_escaping(maybe_bytes: Option<&[u8]>) -> Option<String> {
+    maybe_bytes.map(|bytes| match String::from_utf8(bytes.to_vec()) {
+        Ok(utf8_string) => {
+            let result = string_with_control_characters_escaped(utf8_string);
+            log::info!("bytes {:#?} -> str {}", bytes, result);
```
Comment (hrzlgnm) [inline src-tauri/src/main.rs:78]:
```suggestion
            log::debug!("bytes {:#?} -> str {}", bytes, result);
```

File: src-tauri/src/main.rs [hunk 2]
```diff
@@ -58,16 +58,52 @@ fn timestamp_millis() -> u64 {
...
         let mut sorted_addresses: Vec<IpAddr> = info.get_addresses().clone().drain().collect();
         sorted_addresses.sort();
         let mut sorted_txt: Vec<TxtRecord> = info
             .get_properties()
             .iter()
-            .map(|r| TxtRecord {
-                key: r.key().into(),
-                val: r.val_str().into(),
+            .map(|r| {
+                log::info!("txt prop {:#?}", r.val());
```
Comment (hrzlgnm) [inline src-tauri/src/main.rs:102]:
```suggestion
                log::debug!("txt prop {:#?}", r.val());
```
